# Copyright 2022 Adam Dyess
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  juju_api_endpoints:
    type: string
    default: ""
    description: |
      Juju controller API endpoints separated by commas
  juju_ca_cert:
    type: string
    default: ""
    description: |
      Juju controller CA certificate (base64 encoded)
  juju_username:
    type: string
    default: ""
    description: |
      Juju account username
  juju_password:
    type: string
    default: ""
    description: |
      Juju account password
  juju_refresh_interval:
    type: int
    default: 5
    description: |
      How often to sync against the Juju model.
  juju_model_uuid:
    type: string
    default: ""
    description: |
      Juju model UUID
  juju_scale:
    type: string
    default: ""
    description: |
      Comma separated list of applications to scale prefixed with the minimum and maximum within that node-group.
      
      example)
      3:10:kubernetes-worker-amd64, 0:3:kubernetes-worker-arm64, 0:3:kubernetes-worker-s390x, 0:3:kubernetes-worker-gpu

