# Copyright 2022 Adam Dyess
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  juju_api_endpoint:
    type: string
    default: null
    description: |
      Juju controller API endpoint
  juju_ca_cert:
    type: string
    default: null
    description: |
      Juju controller CA certificate (base64 encoded)
  juju_username:
    type: string
    default: null
    description: |
      Juju account username
  juju_password:
    type: string
    default: null
    description: |
      Juju account password
  juju_refresh_interval:
    type: int
    default: 5
    description: |
      How often to sync against the Juju model.
  juju_model_uuid:
    type: string
    default: null
    description: |
      Juju model UUID
  juju_application:
    type: string
    default: null
    description: |
      Name of the application to scale.

